str1=input("enter the string:")
str2=input("enter the string:")
str3=input("enter the string:")
print(str1.strip())
print(str1.upper())
print(str1.lower())
print(str1.startswith("a"))
print(str1.endswith("a"))
print(str1.isalpha())
print(str2.isalnum())
print(str3.isdigit())
print(str1.count("a"))
print(str1.find("a"))
